version: '3.8'
services:
  transaction-routine-app:
    container_name: transaction-routine-microservice
    build:
      context: ./
      dockerfile: Dockerfile
    image: transaction-routine-microservice:latest
    environment:
      SERVER_PORT: 8090
      MYSQL_URL: jdbc:mysql://mysqldb:3306/transaction-routine-db
      MYSQL_USER: transaction-routine-user
      MYSQL_PASSWORD: transactionroutine123
    ports:
      - "8090:8090"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - transaction-routine-network

  mysqldb:
    container_name: mysql-database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: transaction-routine-db
      MYSQL_USER: transaction-routine-user
      MYSQL_PASSWORD: transactionroutine123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - transaction-routine-network

networks:
  transaction-routine-network:
volumes:
  my-db: