apiVersion: v1
kind: Service
metadata:
  name: transaction-routine-service
  namespace: transaction-routine
spec:
  selector:
    app: transaction-routine-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-https-ssl
      port: 443
      targetPort: http
    - name: server-port
      port: 8090
      targetPort: 8090
  type: NodePort